/**
 * Demo property data: 100 unique properties across UK cities.
 * Descriptions and amenities are varied to showcase semantic search (garden, parking, gym, river view, etc.).
 */
export const DEMO_PROPERTIES = [
  { address: '42 Riverside Drive, London E1', description: 'Two-bedroom flat with river view, modern kitchen and balcony. Quiet building with lift.', amenities: ['parking', 'balcony', 'river view', 'lift'] },
  { address: '15 Oak Lane, Manchester M2', description: 'Spacious three-bed house with private garden and off-street parking. Ideal for families.', amenities: ['garden', 'parking', 'driveway'] },
  { address: '7 Marina Quay, Bristol BS1', description: 'One-bed apartment by the harbour. Marina view, gym and bike storage in building.', amenities: ['gym', 'bike storage', 'harbour view'] },
  { address: '88 High Street, Edinburgh EH1', description: 'Studio with garden access and on-site laundry. Walking distance to shops and transport.', amenities: ['garden', 'laundry', 'central'] },
  { address: '23 Thames View, London SE10', description: 'Two-bed with stunning river view and allocated parking. Secure entry and concierge.', amenities: ['parking', 'river view', 'concierge'] },
  { address: '4 Clifton Gardens, Bristol BS8', description: 'Victorian terrace with large garden and driveway. Near university and harbourside.', amenities: ['garden', 'driveway', 'parking'] },
  { address: '56 Castle Road, Edinburgh EH10', description: 'Three-bed family home with garden and garage. Quiet cul-de-sac.', amenities: ['garden', 'garage', 'parking'] },
  { address: '91 Deansgate, Manchester M3', description: 'City centre apartment with gym and rooftop terrace. Balcony with city views.', amenities: ['gym', 'balcony', 'terrace'] },
  { address: '12 Canal Side, Birmingham B1', description: 'Modern one-bed with canal view. Building has gym and secure bike storage.', amenities: ['gym', 'bike storage', 'canal view'] },
  { address: '33 Meadow Lane, Leeds LS1', description: 'Semi-detached with large garden and shed. Off-street parking for two cars.', amenities: ['garden', 'parking', 'driveway'] },
  { address: '77 Harbour Way, Southampton SO14', description: 'Waterfront two-bed with marina view. Allocated parking and lift.', amenities: ['parking', 'marina view', 'lift'] },
  { address: '19 Park Avenue, Sheffield S1', description: 'Three-bed with garden backing onto park. Driveway and garage.', amenities: ['garden', 'parking', 'garage'] },
  { address: '8 Riverside Walk, Cambridge CB1', description: 'One-bed by the river. Bike storage and shared garden. Central location.', amenities: ['bike storage', 'garden', 'river view'] },
  { address: '44 Hill Street, Glasgow G1', description: 'Two-bed flat with city views. Building has gym and concierge.', amenities: ['gym', 'concierge'] },
  { address: '61 Quay Street, Liverpool L1', description: 'Apartment with river view and balcony. Secure underground parking.', amenities: ['parking', 'balcony', 'river view'] },
  { address: '3 Garden Close, Nottingham NG1', description: 'End-terrace with private garden and parking. Near tram stop.', amenities: ['garden', 'parking'] },
  { address: '28 Marina Gate, Cardiff CF10', description: 'One-bed with harbour view. Gym and bike storage in building.', amenities: ['gym', 'bike storage', 'harbour view'] },
  { address: '50 Oak Drive, Reading RG1', description: 'Three-bed house with garden and driveway. Family-friendly street.', amenities: ['garden', 'driveway', 'parking'] },
  { address: '9 Riverside Court, Newcastle NE1', description: 'Two-bed with river view. Allocated parking and lift access.', amenities: ['parking', 'river view', 'lift'] },
  { address: '72 Lake Road, Leicester LE1', description: 'Semi with garden and garage. Quiet area near park.', amenities: ['garden', 'garage', 'parking'] },
  { address: '5 Waterside, Bristol BS2', description: 'Studio with canal view. On-site laundry and bike storage.', amenities: ['bike storage', 'laundry', 'canal view'] },
  { address: '39 Castle Hill, Edinburgh EH2', description: 'One-bed with castle view. Central, lift building.', amenities: ['lift', 'central'] },
  { address: '84 Green Lane, Manchester M4', description: 'Two-bed with shared garden. On-street permit parking available.', amenities: ['garden'] },
  { address: '21 Dock Road, London E14', description: 'Two-bed apartment with river view. Gym and concierge.', amenities: ['gym', 'concierge', 'river view'] },
  { address: '67 Mill Street, Birmingham B2', description: 'Warehouse conversion with canal view. Secure parking and bike store.', amenities: ['parking', 'bike storage', 'canal view'] },
  { address: '14 Orchard Gardens, Leeds LS2', description: 'Three-bed with large garden and fruit trees. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '93 Sea View Road, Brighton BN1', description: 'One-bed with sea view and balcony. No parking; street permit.', amenities: ['balcony', 'sea view'] },
  { address: '26 Bridge Street, Sheffield S2', description: 'Two-bed near river. Allocated parking and small patio.', amenities: ['parking', 'river view'] },
  { address: '48 Meadow Close, Oxford OX1', description: 'Semi with garden backing meadow. Bike shed and parking.', amenities: ['garden', 'parking', 'bike storage'] },
  { address: '11 Tower Place, Glasgow G2', description: 'High-rise two-bed with city views. Gym and secure entry.', amenities: ['gym'] },
  { address: '55 Quayside, Liverpool L2', description: 'Apartment with river and dock views. Underground parking.', amenities: ['parking', 'river view'] },
  { address: '30 Forest Road, Nottingham NG2', description: 'Three-bed with garden and driveway. Near woodland.', amenities: ['garden', 'driveway'] },
  { address: '76 Harbour Heights, Cardiff CF11', description: 'Two-bed with harbour view. Building has gym and parking.', amenities: ['gym', 'parking', 'harbour view'] },
  { address: '2 Riverside Gardens, Reading RG2', description: 'House with river view and private garden. Off-street parking.', amenities: ['garden', 'parking', 'river view'] },
  { address: '41 Tyne View, Newcastle NE2', description: 'Two-bed with river view. Allocated space and bike store.', amenities: ['parking', 'bike storage', 'river view'] },
  { address: '63 Park Lane, Leicester LE2', description: 'Three-bed overlooking park. Garden and driveway.', amenities: ['garden', 'driveway', 'parking'] },
  { address: '17 Canal Lock, Manchester M1', description: 'One-bed with canal view. Shared courtyard and bike storage.', amenities: ['bike storage', 'canal view'] },
  { address: '88 Victoria Road, London SW1', description: 'Two-bed period conversion. Shared garden; permit parking.', amenities: ['garden'] },
  { address: '52 Mill Lane, Bristol BS3', description: 'Two-bed with small garden. Off-street parking.', amenities: ['garden', 'parking'] },
  { address: '6 Princes Street, Edinburgh EH3', description: 'One-bed on main street. Lift; no parking.', amenities: ['lift', 'central'] },
  { address: '95 Chapel Street, Manchester M5', description: 'Studio with rooftop access. Gym in building.', amenities: ['gym'] },
  { address: '34 Waterfront, Birmingham B3', description: 'Two-bed with canal view. Secure parking and concierge.', amenities: ['parking', 'concierge', 'canal view'] },
  { address: '70 Valley Road, Leeds LS3', description: 'Three-bed with garden and garage. Valley views.', amenities: ['garden', 'garage', 'parking'] },
  { address: '23 Beach Road, Southampton SO15', description: 'Two-bed near marina. One allocated space.', amenities: ['parking', 'marina view'] },
  { address: '59 Botanical Gardens, Sheffield S3', description: 'Semi with garden near botanical gardens. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '81 River Lane, Cambridge CB2', description: 'One-bed by river. Bike storage and shared garden.', amenities: ['bike storage', 'garden', 'river view'] },
  { address: '43 Buchanan Street, Glasgow G3', description: 'Two-bed with city view. Gym and secure entry.', amenities: ['gym'] },
  { address: '15 Albert Dock, Liverpool L3', description: 'Apartment with dock and river view. Underground parking.', amenities: ['parking', 'river view'] },
  { address: '38 Lenton Boulevard, Nottingham NG3', description: 'Three-bed with garden. Driveway for two.', amenities: ['garden', 'driveway'] },
  { address: '64 Bute Street, Cardiff CF12', description: 'One-bed with harbour view. Building gym and parking.', amenities: ['gym', 'parking', 'harbour view'] },
  { address: '7 Thames Street, Reading RG3', description: 'Two-bed with river view. Garden and one space.', amenities: ['garden', 'parking', 'river view'] },
  { address: '29 Quayside Lofts, Newcastle NE3', description: 'Loft-style two-bed, river view. Parking and bike store.', amenities: ['parking', 'bike storage', 'river view'] },
  { address: '91 Aylestone Road, Leicester LE3', description: 'Three-bed with garden and garage. Quiet estate.', amenities: ['garden', 'garage', 'parking'] },
  { address: '4 Salford Quays, Manchester M6', description: 'Two-bed with water view. Gym, parking, balcony.', amenities: ['gym', 'parking', 'balcony'] },
  { address: '66 Chelsea Reach, London SW3', description: 'Two-bed with river view. Concierge and underground parking.', amenities: ['parking', 'concierge', 'river view'] },
  { address: '19 Southville, Bristol BS4', description: 'Two-bed with garden. One off-street space.', amenities: ['garden', 'parking'] },
  { address: '77 Grassmarket, Edinburgh EH4', description: 'One-bed central. No parking; lift in building.', amenities: ['lift', 'central'] },
  { address: '53 MediaCity, Salford M7', description: 'One-bed with water and dock views. Gym and parking.', amenities: ['gym', 'parking'] },
  { address: '36 Brindleyplace, Birmingham B4', description: 'Two-bed canal view. Secure parking and concierge.', amenities: ['parking', 'concierge', 'canal view'] },
  { address: '82 Headingley, Leeds LS4', description: 'Three-bed with garden. Driveway and shed.', amenities: ['garden', 'driveway'] },
  { address: '10 Ocean Village, Southampton SO16', description: 'Two-bed marina view. Allocated parking and balcony.', amenities: ['parking', 'balcony', 'marina view'] },
  { address: '45 Ecclesall Road, Sheffield S4', description: 'Two-bed with garden. On-street permit.', amenities: ['garden'] },
  { address: '73 Chesterton Road, Cambridge CB3', description: 'One-bed near river. Bike storage and garden.', amenities: ['bike storage', 'garden', 'river view'] },
  { address: '25 Finnieston, Glasgow G4', description: 'Two-bed with river view. Gym in building.', amenities: ['gym', 'river view'] },
  { address: '58 Baltic Triangle, Liverpool L4', description: 'Studio with city view. Secure bike storage.', amenities: ['bike storage'] },
  { address: '92 West Bridgford, Nottingham NG4', description: 'Three-bed with garden and driveway. Near Trent.', amenities: ['garden', 'driveway', 'river view'] },
  { address: '20 Cardiff Bay, Cardiff CF13', description: 'Two-bed harbour view. Gym, parking, balcony.', amenities: ['gym', 'parking', 'balcony', 'harbour view'] },
  { address: '86 Kennet Side, Reading RG4', description: 'House with river view and garden. Two spaces.', amenities: ['garden', 'parking', 'river view'] },
  { address: '31 Gateshead Quay, Newcastle NE4', description: 'Two-bed with river view. Parking and lift.', amenities: ['parking', 'lift', 'river view'] },
  { address: '69 Knighton, Leicester LE4', description: 'Three-bed with garden. Driveway and garage.', amenities: ['garden', 'driveway', 'garage'] },
  { address: '13 Spinningfields, Manchester M8', description: 'One-bed city view. Gym and concierge.', amenities: ['gym', 'concierge'] },
  { address: '97 Wapping, London E1', description: 'Two-bed with river view. Secure parking.', amenities: ['parking', 'river view'] },
  { address: '46 Redfield, Bristol BS5', description: 'Two-bed with garden. One parking space.', amenities: ['garden', 'parking'] },
  { address: '62 Newington, Edinburgh EH5', description: 'One-bed with garden access. Permit parking.', amenities: ['garden'] },
  { address: '8 Ancoats, Manchester M9', description: 'Two-bed with balcony. Building has gym.', amenities: ['gym', 'balcony'] },
  { address: '74 Digbeth, Birmingham B5', description: 'Warehouse conversion, canal view. Parking and bike store.', amenities: ['parking', 'bike storage', 'canal view'] },
  { address: '40 Roundhay, Leeds LS5', description: 'Three-bed with large garden. Double driveway.', amenities: ['garden', 'driveway'] },
  { address: '27 Portswood, Southampton SO17', description: 'Two-bed with small garden. One space.', amenities: ['garden', 'parking'] },
  { address: '85 Broomhill, Sheffield S5', description: 'Two-bed with garden. Off-street parking.', amenities: ['garden', 'parking'] },
  { address: '51 Newnham, Cambridge CB4', description: 'One-bed near river and meadows. Bike storage.', amenities: ['bike storage', 'river view'] },
  { address: '18 Partick, Glasgow G5', description: 'Two-bed with river view. Parking available.', amenities: ['parking', 'river view'] },
  { address: '94 Ropewalks, Liverpool L5', description: 'One-bed with balcony. Secure entry.', amenities: ['balcony'] },
  { address: '35 Beeston, Nottingham NG5', description: 'Three-bed with garden and driveway. Near canal.', amenities: ['garden', 'driveway', 'canal view'] },
  { address: '71 Pontcanna, Cardiff CF14', description: 'Two-bed with garden. One space; near park.', amenities: ['garden', 'parking'] },
  { address: '9 Tilehurst, Reading RG5', description: 'Three-bed with garden and garage. Family area.', amenities: ['garden', 'garage', 'parking'] },
  { address: '57 Heaton, Newcastle NE5', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '83 Oadby, Leicester LE5', description: 'Three-bed semi with garden. Garage and driveway.', amenities: ['garden', 'garage', 'driveway'] },
  { address: '22 Northern Quarter, Manchester M10', description: 'Studio with roof terrace. Gym in building.', amenities: ['gym', 'terrace'] },
  { address: '78 Limehouse, London E2', description: 'Two-bed with river view. Allocated parking.', amenities: ['parking', 'river view'] },
  { address: '1 Easton, Bristol BS6', description: 'Two-bed with garden. Bike shed and parking.', amenities: ['garden', 'parking', 'bike storage'] },
  { address: '49 Morningside, Edinburgh EH6', description: 'Two-bed with garden access. Permit parking.', amenities: ['garden'] },
  { address: '90 Hulme, Manchester M11', description: 'Two-bed with balcony. Shared garden.', amenities: ['balcony', 'garden'] },
  { address: '16 Jewellery Quarter, Birmingham B6', description: 'One-bed canal view. Secure parking.', amenities: ['parking', 'canal view'] },
  { address: '54 Chapel Allerton, Leeds LS6', description: 'Three-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '32 Bitterne, Southampton SO18', description: 'Two-bed with garden. One off-street space.', amenities: ['garden', 'parking'] },
  { address: '98 Crookes, Sheffield S6', description: 'Two-bed with garden and parking. Near university.', amenities: ['garden', 'parking'] },
  { address: '24 Arbury, Cambridge CB5', description: 'One-bed with shared garden. Bike storage.', amenities: ['bike storage', 'garden'] },
  { address: '60 Shawlands, Glasgow G6', description: 'Two-bed with garden. On-street permit.', amenities: ['garden'] },
  { address: '11 Smithdown, Liverpool L6', description: 'Two-bed with small garden. Permit parking.', amenities: ['garden'] },
  { address: '87 Sherwood, Nottingham NG6', description: 'Three-bed with garden and driveway.', amenities: ['garden', 'driveway'] },
  { address: '42 Roath, Cardiff CF15', description: 'Two-bed with garden. One space; near lake.', amenities: ['garden', 'parking'] },
  { address: '68 Caversham, Reading RG6', description: 'Three-bed with river view and garden. Two spaces.', amenities: ['garden', 'parking', 'river view'] },
  { address: '37 Jesmond, Newcastle NE6', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '75 Evington, Leicester LE6', description: 'Three-bed with large garden. Garage.', amenities: ['garden', 'garage', 'parking'] },
  { address: '5 Chorlton, Manchester M12', description: 'Two-bed with garden and bike store. Permit parking.', amenities: ['garden', 'bike storage'] },
  { address: '89 Bermondsey, London SE1', description: 'Two-bed with river view. Secure parking.', amenities: ['parking', 'river view'] },
  { address: '47 Bedminster, Bristol BS7', description: 'Two-bed with garden. One parking space.', amenities: ['garden', 'parking'] },
  { address: '65 Corstorphine, Edinburgh EH7', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '26 Withington, Manchester M13', description: 'Two-bed with garden. On-street permit.', amenities: ['garden'] },
  { address: '79 Bournville, Birmingham B7', description: 'Three-bed with garden and garage. Village feel.', amenities: ['garden', 'garage', 'parking'] },
  { address: '52 Horsforth, Leeds LS7', description: 'Three-bed with garden. Driveway for two.', amenities: ['garden', 'driveway'] },
  { address: '33 Shirley, Southampton SO19', description: 'Two-bed with garden. One space.', amenities: ['garden', 'parking'] },
  { address: '100 Walkley, Sheffield S7', description: 'Two-bed with garden and parking. Valley view.', amenities: ['garden', 'parking'] },
  { address: '12 Trumpington, Cambridge CB6', description: 'One-bed with garden. Bike storage.', amenities: ['garden', 'bike storage'] },
  { address: '71 Pollokshields, Glasgow G7', description: 'Two-bed with garden. Permit parking.', amenities: ['garden'] },
  { address: '38 Wavertree, Liverpool L7', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '56 Arnold, Nottingham NG7', description: 'Three-bed with garden and driveway.', amenities: ['garden', 'driveway'] },
  { address: '84 Canton, Cardiff CF16', description: 'Two-bed with garden. One space.', amenities: ['garden', 'parking'] },
  { address: '20 Woodley, Reading RG7', description: 'Three-bed with garden and garage.', amenities: ['garden', 'garage', 'parking'] },
  { address: '93 Gosforth, Newcastle NE7', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '61 Syston, Leicester LE7', description: 'Three-bed with garden and garage.', amenities: ['garden', 'garage', 'parking'] },
  { address: '44 Didsbury, Manchester M14', description: 'Two-bed with garden and parking. Near metro.', amenities: ['garden', 'parking'] },
  { address: '17 Rotherhithe, London SE16', description: 'Two-bed with river view. Allocated parking.', amenities: ['parking', 'river view'] },
  { address: '55 St Werburghs, Bristol BS8', description: 'Two-bed with garden and bike store.', amenities: ['garden', 'bike storage'] },
  { address: '73 Stockbridge, Edinburgh EH8', description: 'One-bed with river view. Central.', amenities: ['river view', 'central'] },
  { address: '30 Fallowfield, Manchester M15', description: 'Two-bed with garden. Student area; permit parking.', amenities: ['garden'] },
  { address: '81 Erdington, Birmingham B8', description: 'Three-bed with garden and driveway.', amenities: ['garden', 'driveway'] },
  { address: '6 Pudsey, Leeds LS8', description: 'Three-bed with large garden. Double driveway.', amenities: ['garden', 'driveway'] },
  { address: '95 Netley, Southampton SO20', description: 'Two-bed with garden and one space.', amenities: ['garden', 'parking'] },
  { address: '39 Dore, Sheffield S8', description: 'Two-bed with garden. Off-street parking.', amenities: ['garden', 'parking'] },
  { address: '28 Histon, Cambridge CB7', description: 'One-bed with garden. Bike storage.', amenities: ['garden', 'bike storage'] },
  { address: '86 Govan, Glasgow G8', description: 'Two-bed with river view. Parking.', amenities: ['parking', 'river view'] },
  { address: '50 Allerton, Liverpool L8', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '72 Carlton, Nottingham NG8', description: 'Three-bed with garden and driveway.', amenities: ['garden', 'driveway'] },
  { address: '14 Llandaff, Cardiff CF17', description: 'Two-bed with garden. One space; near river.', amenities: ['garden', 'parking', 'river view'] },
  { address: '99 Earley, Reading RG8', description: 'Three-bed with garden and garage.', amenities: ['garden', 'garage', 'parking'] },
  { address: '35 Fenham, Newcastle NE8', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '77 Wigston, Leicester LE8', description: 'Three-bed with garden and garage.', amenities: ['garden', 'garage', 'parking'] },
  { address: '63 Levenshulme, Manchester M16', description: 'Two-bed with garden. Permit parking.', amenities: ['garden'] },
  { address: '2 Surrey Quays, London SE8', description: 'Two-bed with river view. Secure parking.', amenities: ['parking', 'river view'] },
  { address: '69 Cotham, Bristol BS9', description: 'Two-bed with garden. One space.', amenities: ['garden', 'parking'] },
  { address: '41 Marchmont, Edinburgh EH9', description: 'One-bed with garden access. Central.', amenities: ['garden', 'central'] },
  { address: '88 Rusholme, Manchester M17', description: 'Two-bed with small garden. Curry mile area.', amenities: ['garden'] },
  { address: '19 Yardley, Birmingham B9', description: 'Three-bed with garden and driveway.', amenities: ['garden', 'driveway'] },
  { address: '53 Otley, Leeds LS9', description: 'Three-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '10 Eastleigh, Southampton SO21', description: 'Two-bed with garden. One space.', amenities: ['garden', 'parking'] },
  { address: '96 Totley, Sheffield S9', description: 'Two-bed with garden and parking. Edge of peak district.', amenities: ['garden', 'parking'] },
  { address: '64 Grantchester, Cambridge CB8', description: 'One-bed near river. Garden and bike store.', amenities: ['garden', 'bike storage', 'river view'] },
  { address: '21 Gorbals, Glasgow G9', description: 'Two-bed with river view. Regenerated area.', amenities: ['river view'] },
  { address: '59 Childwall, Liverpool L9', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '85 West Bridgford, Nottingham NG9', description: 'Three-bed with garden and driveway. Near Trent.', amenities: ['garden', 'driveway', 'river view'] },
  { address: '36 Splott, Cardiff CF18', description: 'Two-bed with garden. One space.', amenities: ['garden', 'parking'] },
  { address: '70 Lower Earley, Reading RG9', description: 'Three-bed with garden and garage.', amenities: ['garden', 'garage', 'parking'] },
  { address: '43 Benton, Newcastle NE9', description: 'Two-bed with garden. Driveway.', amenities: ['garden', 'driveway'] },
  { address: '80 Loughborough, Leicester LE9', description: 'Three-bed with garden and garage. University town.', amenities: ['garden', 'garage', 'parking'] },
  { address: '34 Burnage, Manchester M18', description: 'Two-bed with garden. Permit parking.', amenities: ['garden'] },
  { address: '92 Deptford, London SE10', description: 'Two-bed with river view. Regenerated area.', amenities: ['river view'] },
  { address: '58 Henbury, Bristol BS10', description: 'Two-bed with garden. One space.', amenities: ['garden', 'parking'] },
  { address: '15 Duddingston, Edinburgh EH10', description: 'Two-bed with loch view. Garden and parking.', amenities: ['garden', 'parking'] },
];

/** One lease per property (varied rent and dates). */
function buildLeaseForProperty(index: number) {
  const baseRent = 800 + (index % 25) * 40;
  const startYear = 2024 + (index % 2);
  const startMonth = (index % 12) + 1;
  const startDay = (index % 28) + 1;
  const start = `${startYear}-${String(startMonth).padStart(2, '0')}-${String(startDay).padStart(2, '0')}`;
  const endYear = startYear + 1;
  const endMonth = startMonth;
  const endDay = Math.min(startDay, 28);
  const end = `${endYear}-${String(endMonth).padStart(2, '0')}-${String(endDay).padStart(2, '0')}`;
  return {
    extractedTerms: {
      monthlyRent: baseRent,
      deposit: baseRent * 2,
      startDate: start,
      endDate: end,
      tenantName: index % 3 === 0 ? 'Tenant' : undefined,
    },
    status: index % 4 === 0 ? 'draft' : 'confirmed',
  };
}

/** One maintenance description per property (rotates through a pool to limit Gemini calls but keep variety). */
const DEMO_MAINTENANCE_POOL = [
  'Kitchen tap dripping; mould under sink.',
  'Heating not working in living room.',
  'Broken window latch in bedroom.',
  'Light fitting in hallway flickers.',
  'Toilet running constantly.',
  'Radiator cold in spare room.',
  'Extractor fan in bathroom noisy.',
  'Front door lock stiff.',
  'Damp patch on bedroom wall.',
  'Oven not heating evenly.',
  'Smoke alarm beeping.',
  'Gutter leaking above front door.',
  'Boiler pressure low.',
  'Shower head blocked.',
  'Back door won’t close properly.',
  'Carpet lifting on stairs.',
  'Fuse tripping when using kettle.',
  'Letterbox draft.',
  'Sink waste slow to drain.',
  'Curtain rail loose.',
];

export function getLeaseForProperty(index: number) {
  return buildLeaseForProperty(index);
}

export function getMaintenanceForProperty(index: number): string {
  return DEMO_MAINTENANCE_POOL[index % DEMO_MAINTENANCE_POOL.length];
}
